export const DEFAULT_SPECIALTIES = [
  "General Nursing",
  "Pediatrics",
  "Cardiology",
  "Oncology",
  "Neurology",
  "Mental Health",
  "Psychiatry",
  "Orthopedics",
  "Emergency Care",
  "ICU",
  "Neonatal Care",
  "Dermatology",
  "Community Health",
  "Women's Health",
  "Men's Health",
  "Nutrition",
  "Diabetes",
  "Hypertension",
  "Infectious Diseases",
  "Maternal Care",
];